- hosts: apps
  tasks:
    - name: Install Nginx
      apt: pkg=nginx state=latest
      notify:
       - Ensure Nginx Is Started

  handlers:
    - name: Ensure Nginx Is Started
      service: name=nginx state=started