version: '3'
services:
  gateway:
    build:
      context: ./src/GateWay
      dockerfile: Dockerfile.GateWay
    ports: '8989:80'
    environment:
      AMORTIZATION_CALCULATOR_SERVICE_ADDRESS: 'localhost:8987'
      INTEREST_RATE_CALCULATOR_SERVICE_ADDRESS: 'localhost:8988'
    depends_on:
      interest_rate_calculator:
        condition: service_healthy
      amortization_calculator:
        condition: service_healthy

  amortization_calculator:
    build:
      context: ./src/AmortizationCalculator
      dockerfile: Dockerfile.Dockerfile.AmortizationCalculator
    ports: '8987:80'

  interest_rate_calculator:
    build:
      context: ./src/InterestRateCalculator
      dockerfile: Dockerfile.InterestRateCalculator
    ports: '8988:80'
