version: '3'
services:
  consul:
    image: consul:1.11
    container_name: consul
    ports: ['8500:8500']
    networks:
      interest_rate_network:
        ipv4_address: '${CONSUL_IP}'
    
  amortization_calculator:
    image: amortization_calculator:v1
    container_name: amortization_calculator
    ports: ['8987:80']
    networks:
      interest_rate_network:
        ipv4_address: '${AMORTIZATION_CALCULATOR_SERVICE_IP}'

  interest_rate_calculator:
    image: interest_rate_calculator:v1
    container_name: interest_rate_calculator
    ports: ['8988:80']
    networks:
      interest_rate_network:
        ipv4_address: '${INTEREST_RATE_CALCULATOR_SERVICE_IP}'
    
  gateway:
    image: gateway:v1
    container_name: gateway
    ports: ['8989:80']
    environment:
      AMORTIZATION_CALCULATOR_SERVICE_ADDRESS: '${AMORTIZATION_CALCULATOR_SERVICE_ADDRESS}'
      INTEREST_RATE_CALCULATOR_SERVICE_ADDRESS: '${INTEREST_RATE_CALCULATOR_SERVICE_ADDRESS}'
      CONSUL_ADDRESS: '${CONSUL_ADDRESS}'
      SERVICE_ADDRESS: '${GATEWAY_ADDRESS}'
    depends_on:
      - interest_rate_calculator
      - amortization_calculator
      - consul
    networks:
      interest_rate_network:
        ipv4_address: '${GATEWAY_IP}'

networks:
  interest_rate_network:
    driver: bridge
    ipam:
      config:
        - subnet: 33.22.11.0/16