name: CI

on:
  push:
    branches: [ main, develop, release ]
  pull_request:
    branches: [ develop ]

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Restore dependencies
      run: |
        dotnet restore "src/AmortizationCalculator"
        dotnet restore "src/GateWay"
        dotnet restore "src/InterestRateCalculator"
    - name: Build Projects
      run: |
        dotnet build "src/AmortizationCalculator" --no-restore
        dotnet build "src/GateWay" --no-restore
        dotnet build "src/InterestRateCalculator" --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Run Unit Tests
      run: |
        dotnet test "src/AmortizationCalculator" --no-build --verbosity normal
        dotnet test "src/GateWay" --no-build --verbosity normal
        dotnet test "src/InterestRateCalculator" --no-build --verbosity normal
